apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app
  labels:
    app: 2048-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-app
  template: 
    metadata:
      labels: 
        app: 2048-app
    spec:
      conatiners: 
      - name: ss
        image: sss
        ports:
        - containerPort: 8080 